name: CI

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Inspect GitHub OIDC Token
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq '.'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.PROJECT_ID }}:role/GitHubActionsECRPushRole
          aws-region: ap-northeast-1

      - name: Docker login & Push
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
          ls -la
          cd ./gitlabs/docker          
          docker build -t ${{ secrets.ECR_REPO }}/ryota:latest .
          docker push ${{ secrets.ECR_REPO }}/ryota:latest
